website/campaigns/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField, RadioField, SelectField, Field
from wtforms.validators import DataRequired
from  wtforms.widgets import Input, Select, CheckboxInput 

class InstagramLogInForm(FlaskForm):
    username = StringField(u'Username', validators=[DataRequired()])
    submit = SubmitField('Put me on a screen in LA')
class SettingsForm(FlaskForm):
    business = RadioField(u'Business or non-business', choices=[('yes-busi','Business'),('no-busi','Non-business'),('both','Both')])
    control_content = RadioField(u'Control of Content', choices=[("owner",'I own the Instagram account'),("none-owner","The Instagram account is someone else's")])
    social = RadioField(u'Important Social Media', choices=[('newsfeed','Twitter/Facebook'),('instagram','Instagram'),('videosite','Youtube'),('reviewsite','Yelp'),('own website', 'Your website'),('aggregator','Reddit')])
    submit = SubmitField('Save')

website/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired,Length, Email, EqualTo, ValidationError
from website.models import User

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    password = PasswordField('Password', validators=[DataRequired(),])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(),EqualTo('password')] )
    submit = SubmitField('Sign Up')
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is already used.')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    password = PasswordField('Password', validators=[DataRequired(),])
    remember = BooleanField('Remember Me')
    submit = SubmitField('LogIn')

website/campaigns/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required, logout_user
import json
import requests
from website import db
from website.campaigns.forms import SettingsForm
from website.config import config
from website.models import Campaign
import pdb
from pprint import pprint

campaigns = Blueprint('campaigns', __name__)

@campaigns.route("/campaign", methods =['POST','GET'])
#@login_required
def campaign():
    if current_user.is_active == False:
        return(redirect(url_for('main.home')))
    campaign = campaign_retrieve(current_user.id)
    settings = SettingsForm()
    if campaign == "home":
        return redirect(url_for('users.logout'))
    #if settings.validate_on_submit():
    #None is in quotes and the "!=" is used instead of "is not" because that's currently getting pyhton to correctly behave
    if (settings.data.get("control_content") != "None"):
        campaign.sett_control_content = settings.data.get('control_content')
    if (settings.data.get("business") != "None"):
        campaign.sett_business = settings.data.get('business')
    if (settings.data.get("social") != "None"):
        campaign.sett_social = settings.data.get('social')
    db.session.commit()
    return (render_template('campaign.html', settings = settings, campaign = campaign,title='WaiveAd'))

def campaign_retrieve(username):
    campaign = Campaign.query.filter_by(user_id=username).first()
    if campaign == None:
        return "home"
    ig_username = campaign.ig_username
    url = "http://staging.waivescreen.com/api/campaign_history?ref_id="+ig_username
    req = requests.get(url)
    campaign_db = req.text
    campaign_json = json.loads(campaign_db)
    if campaign.lat != None and (round(campaign_json['lat'],2) == round(campaign.lat,2) or round(campaign_json['lng'],2) == round(campaign.lng,2)):
        return campaign
    else:
        campaign.lat = campaign_json['lat']
        campaign.lng = campaign_json['lng']
        url = "https://api.opencagedata.com/geocode/v1/json?q="+str(campaign_json['lat'])+","+str(campaign_json['lng'])+"&pretty=1&key=af0c0f848c3647ed9ed39e8f9747f0b3"
        req = requests.get(url)
        addr_json = json.loads(req.text)
        addr_json = addr_json['results']
        city = addr_json[0]
        city = city['components']
        city = city['suburb']
        campaign.last_city = city
        print(city)
        db.session.commit()
        return campaign

website/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import current_user, login_required, login_user, logout_user
from website import db, bcrypt
from website.users.forms import RegistrationForm, LoginForm
from website.models import User


users = Blueprint('users', __name__)

@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Log In Unsuccessful, please check email and password', 'danger')
    return (render_template('login.html',title='Login',form=form))

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account successfully created for '+user.email+'!','success')
        login_user(user)
        return redirect(url_for('users.user'))
    return (render_template('register.html', title='Register',form=form))

@users.route("/user")
@login_required
def user():
    if current_user.is_authenticated:
        return (render_template('user.html',title='User'))
    else:
        flash('You are not logged in', 'danger')

website/website/campaigns/routes.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required
from website import db
from website.models import Campaign

campaigns = Blueprint('campaigns', __name__)

@campaigns.route("/campaign")
@login_required
def campaign():
    return (render_template('campaign.html',title='WaiveAd'))

website/templates/campaign.html
{% extends 'layout.html' %}
{% block body %}
<div style ="margin-top:2vh" class = "container">
  Your Instagram just played in
  <h3>
   {% if campaign.last_city==None %}
   Los Angeles
   {% else %}
   {{campaign.last_city}}
   {% endif %}
  </h3>
  <div class="container">
   <iframe id="ig-frame"src="https://9ol.es/ad-new/?user={{campaign.ig_username}}"height="100vh"> </iframe>
  </div>
   <div id="setting-div">
   <hr size=2>
   <h4> Settings </h4>
   <form action="" method="POST">
    {{ settings.hidden_tag() }}
    <div class="form-group">
     <div class="font-weight-bold"> Ownership</div>
     <div class ="questions" data-toggle="buttons">
      {%for field in settings.control_content%}
      <label class = "btn btn-outline-primary 
      {%if campaign.sett_control_content == field.data%}
       active
      {%endif%}
      ">{{field.label}} {{field}}</label>
      <br>
      {%endfor%}
     </div>
    </div>
    <div class="form-group">
     <div class="font-weight-bold">Type of account</div>
     <div class ="questions" data-toggle="buttons">
     {%for field in settings.business%}
      <label class = "btn btn-outline-primary
      {%if campaign.sett_business == field.data%}
       active
      {%endif%}
      ">{{field.label}} {{field}}</label>
      <br>
     {%endfor%}
     </div>
    </div>
    <hr size=2>
    <div class="form-group">
     <h4> Your next step!</h4>
     <div class="font-weight-bold">What's most important to you?</div>
     <div class ="questions" data-toggle="buttons">
     {%for field in settings.social%}
      <label class = "btn btn-outline-primary
      {%if campaign.sett_social == field.data%}
       active
      {%endif%}">{{field.label}} {{field}}</label>
      <br>
     {%endfor%}
     </div>
    </div>
    <section class="text-center">
    {{settings.submit(class="btn btn-outline-info")}}
    </section>
   </form>
   <br>
 </div>
</div>
{% endblock %}

website/templates/index.html
{% extends 'layout.html' %}
{% block body %}
  <div id=bg>
   <img id=bg-cover src={{url_for('static',filename='media/instaback.jpg')}}>
    <div id=fg>
     <h5 id=hero>Instantly promote yourself IRL through your instagram</h5>
     <div id = "main"class="container">
      <p>
      All you need to do is just type in your insta, we'll put up your most recent 6 posts.
      </p>
      <form class='form' method="post" action="">
       {{ form.hidden_tag() }}
        <div class="form-group">
         <input class="form-control form-control-md" id="username" name="username" required="" placeholder="@username" type="text" value="">
        </div>
        <div class="text-center">
         {{form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
      </div>
    </div>
    <div id=footer>
      <h5> This experiment ends August 31 2019. </h5> 
    </div>
 </div>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang = "en">
 <head>
   <title>WaiveAd</title>
  <meta charset = "utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--Latest stylesheet, as of 08/03/19, needed to run Bootstrap 4 -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <!-- For cool icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='main.css')}}">
  <!-- Fonts that are used -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">

  </head>
  <body>
    <main role="main">
      <div>
        {% with messages=get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{category}}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block body %} {% endblock %}
      </div>
    </main>
    <!--
    <footer class = "page-footer fixed-bottom mt-2  text-center">
      <div class = "container-fluid bg-dark text-white">
        ©2019, Waive. <a href="mailto:support@waivecar.com">Contact</a>
      </div>
    </footer>
    -->

    <!--3 latest scripts, as of 08/03/19, needed to run Bootstrap 4 -->
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

website/templates/login.html
{% extends 'layout.html' %}
{% block body %}
  <div class="content-section">
    <form action="" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class='border-bottom mb-4'>Log In</legend>
        <div class="form-group">
          {{form.email.label(class="form-control-label")}}
          {% if form.email.errors %}
            {{form.email(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{form.email(class="form-control form-control-lg")}}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.password.label(class="form-control-label")}}
          {{form.password(class="form-control form-control-lg")}}
        </div>
        <div class="form-check">
          {{form.remember(class="form-check-input")}}
          {{form.remember.label(class="form-check-label")}}
        </div>
      </fieldset>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
      <small class="text-muted ml-2">
        <a href="#">Forgot Passsword?</a>
      </small>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up Now</a>
    </small>
  </div>
{% endblock %}

website/templates/register.html
{% extends 'layout.html' %}
{% block body %}
  <div class="content-section">
    <form action="" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class='border-bottom mb-4'>Start Advertising</legend>
        <div class="form-group">
          {{form.email.label(class="form-control-label")}}
          {% if form.email.errors %}
            {{form.email(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{form.email(class="form-control form-control-lg")}}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.password.label(class="form-control-label")}}
          {%if form.password.errors %}
            {{form.password(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.name.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
              {{form.password(class="form-control form-control-lg")}}
            {% endif %}
        </div>
        <div class="form-group">
          {{form.confirm_password.label(class="form-control-label")}}
          {% if form.confirm_password.errors %}
            {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
              {% endfor  %}
            </div>
            {% else %}
              {{form.confirm_password(class="form-control form-control-lg")}}
            {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Already Have An Account? <a class="ml-2" href="/login">Sign In</a>
    </small>
  </div>
{% endblock %}

website/templates/user.html
{% extends 'layout.html' %}
{% block body %}
<div class="container content-section">
  <h3> Email: {{current_user.email}} </h3>
  <div class="row">
    <div class="col">
      <h4> Campaigns: </h4>
      {% if current_user.campaigns %}

      {% else %}
        <a href="{{url_for('campaigns.campaign')}}">Lack of campaigns</a>
      {% endif %}
    </div>
    <div class="col">
      <h3>Connections:</h3>
      <h3>Instagram</h3>
      {% if current_user.instagram_auth %}

      {% else %}
        <form method="post">
          <a href="https://api.instagram.com/oauth/authorize/?client_id=2061511199cc4006b94a78f1f9324c99&redirect_uri=https://preview.waivescreen.com/callback/&response_type=code">
          <button id="instagram-buttton" type="button">Instagram Authentication</button> </a>
        </form>
      {% endif %}
    </div>
    <div class="col">
      <h3>Payments</h3>

    </div>
  </div>
  <div class="container">

    <div class="row">
      <div class="col">

      </div>
    </div>
  </div>
</div>
{% endblock %}